# Dataset Profiling

## Objective

The objective of this notebook is to analyze the collected training datasets before creating the master dataset. This includes examining the dataset structure, checking missing values, duplicate records, data types, statistical summaries, and overall data quality. The analysis will help determine which datasets are suitable for merging and further preprocessing for machine learning.

Dataset Profiling

Dataset profiling is the process of analyzing a dataset to understand its quality, completeness, structure, and statistical properties before preprocessing and model training.

After profiling, we identified the number of rows, columns, missing values, duplicate records, and data types of each dataset. This information will help us create the master dataset in the next phase.

In [3]:
import pandas as pd
import numpy as np
import os

In [5]:
# Display current working directory

import os

print("Current Working Directory:")
print(os.getcwd())

Current Working Directory:
D:\Major Project\02_Machine Learning\Notebooks

First Dataset:

In [18]:
import os

dataset_folder = "../../01_Datasets/Training Datasets"

print("Dataset Folder Exists:", os.path.exists(dataset_folder))
print("Files:")

for file in os.listdir(dataset_folder):
    print(file)

Dataset Folder Exists: True
Files:
Dataset01filtered.csv
Dataset02Filtered.csv
Dataset03Filtered.csv
Dataset04Filtered.csv
Dataset09Filtered.csv
Dataset10Filtered.csv

In [13]:
import os

# Get all CSV files from Training Datasets folder

dataset_files = [file for file in os.listdir(dataset_folder) if file.endswith(".csv")]

print("Training Datasets Found:\n")

for i, file in enumerate(dataset_files, start=1):
    print(f"{i}. {file}")

Training Datasets Found:

1. Dataset01filtered.csv
2. Dataset02Filtered.csv
3. Dataset03Filtered.csv
4. Dataset04Filtered.csv
5. Dataset09Filtered.csv
6. Dataset10Filtered.csv

In [14]:
first_dataset = os.path.join(dataset_folder, dataset_files[0])

df = pd.read_csv(first_dataset)

print(df.head())

     pH  Temperature  Turbidity  Total Dissolved Solids  Conductivity  \
0  7.42        16.88       0.25                   306.7        1486.1
1  8.18        20.55       0.87                    84.3         476.3
2  5.58        26.25       1.99                   676.7         479.9
3  7.93        30.15       0.06                   852.9         713.5
4  8.37        12.32       3.37                   161.2        1702.6

   Dissolved Oxygen  Hardness  Nitrate  Chloride  BOD    Target
0              7.41       NaN      NaN       NaN  NaN      Good
1              6.04       NaN      NaN       NaN  NaN  Moderate
2              6.71       NaN      NaN       NaN  NaN      Poor
3              3.24       NaN      NaN       NaN  NaN      Poor
4              6.83       NaN      NaN       NaN  NaN      Poor

In [15]:
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 450
Columns : 11

In [16]:
print(df.columns.tolist())

['pH', 'Temperature', 'Turbidity', 'Total Dissolved Solids', 'Conductivity', 'Dissolved Oxygen', 'Hardness', 'Nitrate', 'Chloride', 'BOD', 'Target']

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450 entries, 0 to 449
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   pH                      450 non-null    float64
 1   Temperature             450 non-null    float64
 2   Turbidity               450 non-null    float64
 3   Total Dissolved Solids  450 non-null    float64
 4   Conductivity            450 non-null    float64
 5   Dissolved Oxygen        450 non-null    float64
 6   Hardness                0 non-null      float64
 7   Nitrate                 0 non-null      float64
 8   Chloride                0 non-null      float64
 9   BOD                     0 non-null      float64
 10  Target                  450 non-null    object
dtypes: float64(10), object(1)
memory usage: 38.8+ KB

Second Dataset:

In [19]:
# Read Dataset02

second_dataset = os.path.join(dataset_folder, dataset_files[1])

df = pd.read_csv(second_dataset)

In [20]:
df.head()

,pH,Temperature,Turbidity,Total Dissolved Solids,Conductivity,Dissolved Oxygen,Hardness,Nitrate,Chloride,BOD,Target
0,8.762414,16.461631,14.468306,NaN,NaN,6.258335,NaN,NaN,NaN,2.478582,2
1,7.477966,27.446865,1.905645,NaN,NaN,2.826120,NaN,NaN,NaN,8.048453,2
2,7.938278,34.623557,1.889506,NaN,NaN,3.380191,NaN,NaN,NaN,2.102481,2
3,8.728748,18.802153,0.736115,NaN,NaN,6.543794,NaN,NaN,NaN,6.714160,2
4,7.975335,30.851902,19.151777,NaN,NaN,4.370861,NaN,NaN,NaN,2.114614,2

In [21]:
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 1000
Columns : 11

In [22]:
df.columns.tolist()

['pH',
 'Temperature',
 'Turbidity',
 'Total Dissolved Solids',
 'Conductivity',
 'Dissolved Oxygen',
 'Hardness',
 'Nitrate',
 'Chloride',
 'BOD',
 'Target']

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   pH                      1000 non-null   float64
 1   Temperature             1000 non-null   float64
 2   Turbidity               1000 non-null   float64
 3   Total Dissolved Solids  0 non-null      float64
 4   Conductivity            0 non-null      float64
 5   Dissolved Oxygen        1000 non-null   float64
 6   Hardness                0 non-null      float64
 7   Nitrate                 0 non-null      float64
 8   Chloride                0 non-null      float64
 9   BOD                     1000 non-null   float64
 10  Target                  1000 non-null   int64
dtypes: float64(10), int64(1)
memory usage: 86.1 KB

Third Dataset:

In [26]:
# Read Dataset03

third_dataset = os.path.join(dataset_folder, dataset_files[2])

df = pd.read_csv(third_dataset)

In [27]:
df.head()

,pH,Temperature,Turbidity,Total Dissolved Solids,Conductivity,Dissolved Oxygen,Hardness,Nitrate,Chloride,BOD,Target
0,7.5,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,7.5,17.5,NaN,NaN,NaN,12.0,NaN,NaN,NaN,NaN,NaN
2,8.0,23.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,8.0,25.5,NaN,NaN,NaN,12.0,NaN,NaN,NaN,NaN,NaN
4,8.5,28.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 2370
Columns : 11

In [29]:
df.columns.tolist()

['pH',
 'Temperature',
 'Turbidity',
 'Total Dissolved Solids',
 'Conductivity',
 'Dissolved Oxygen',
 'Hardness',
 'Nitrate',
 'Chloride',
 'BOD',
 'Target']

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2370 entries, 0 to 2369
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   pH                      2276 non-null   float64
 1   Temperature             2250 non-null   float64
 2   Turbidity               0 non-null      float64
 3   Total Dissolved Solids  0 non-null      float64
 4   Conductivity            0 non-null      float64
 5   Dissolved Oxygen        1520 non-null   float64
 6   Hardness                0 non-null      float64
 7   Nitrate                 0 non-null      float64
 8   Chloride                0 non-null      float64
 9   BOD                     0 non-null      float64
 10  Target                  0 non-null      float64
dtypes: float64(11)
memory usage: 203.8 KB

Dataset4:

In [47]:
# Read Dataset04

fourth_dataset = os.path.join(dataset_folder, dataset_files[3])

df = pd.read_csv(fourth_dataset)

In [48]:
df.head()

,pH,Temperature,Turbidity,Total Dissolved Solids,Conductivity,Dissolved Oxygen,Hardness,Nitrate,Chloride,BOD,Target,Sulfate,Fluoride,Iron
0,8.332988,NaN,0.022683,332.118789,471.683357,NaN,NaN,8.605777,122.799772,NaN,0,87.266538,0.607283,0.000083
1,6.917863,15.348981,0.019007,284.641984,432.844908,NaN,NaN,3.734167,227.029851,NaN,0,144.010981,0.622874,0.000081
2,5.443762,11.643467,0.319956,570.054094,990.201209,NaN,NaN,3.816994,230.995630,NaN,0,275.702107,0.423423,0.020106
3,7.955339,10.092392,0.166319,100.043838,237.028467,NaN,NaN,8.224944,178.129940,NaN,0,147.163233,0.208454,0.143988
4,8.091909,15.249416,0.004867,168.075545,385.025855,NaN,NaN,9.925788,186.540872,NaN,0,175.275175,0.222912,0.002167

In [49]:
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 1048575
Columns : 14

In [50]:
df.columns.tolist()

['pH',
 'Temperature',
 'Turbidity',
 'Total Dissolved Solids',
 'Conductivity',
 'Dissolved Oxygen',
 'Hardness',
 'Nitrate',
 'Chloride',
 'BOD',
 'Target',
 'Sulfate',
 'Fluoride',
 'Iron']

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 14 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   pH                      1028344 non-null  float64
 1   Temperature             1018887 non-null  float64
 2   Turbidity               1039881 non-null  float64
 3   Total Dissolved Solids  1048277 non-null  float64
 4   Conductivity            1019772 non-null  float64
 5   Dissolved Oxygen        0 non-null        float64
 6   Hardness                0 non-null        float64
 7   Nitrate                 1029880 non-null  float64
 8   Chloride                1017741 non-null  float64
 9   BOD                     0 non-null        float64
 10  Target                  1048575 non-null  int64
 11  Sulfate                 1014050 non-null  float64
 12  Fluoride                1015357 non-null  float64
 13  Iron                    1041584 non-null  float64
dtypes: float64(13), int64(1)
memory usage: 112.0 MB

Dataset9:

In [52]:
# Read Dataset02

fifth_dataset = os.path.join(dataset_folder, dataset_files[4])

df = pd.read_csv(fifth_dataset)

In [53]:
df.head()

,pH,Temperature,Turbidity,Total Dissolved Solids,Conductivity,Dissolved Oxygen,Hardness,Nitrate,Chloride,BOD,Status,WQI
0,8.879727,22.650238,NaN,NaN,0.044698,8.630526,NaN,NaN,NaN,NaN,Fair,20.504530
1,8.866815,22.567017,NaN,NaN,0.044651,8.644233,NaN,NaN,NaN,NaN,Fair,20.359197
2,12.359906,18.400787,NaN,NaN,46.195190,13.501176,NaN,NaN,NaN,NaN,Very Poor,42.014328
3,12.825684,18.013641,NaN,NaN,52.609680,9.458531,NaN,NaN,NaN,NaN,Very Poor,47.745434
4,12.998978,18.184570,NaN,NaN,52.399826,12.409351,NaN,NaN,NaN,NaN,Very Poor,46.925593

In [54]:
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 46528
Columns : 12

In [55]:
df.columns.tolist()

['pH',
 'Temperature',
 'Turbidity',
 'Total Dissolved Solids',
 'Conductivity',
 'Dissolved Oxygen',
 'Hardness',
 'Nitrate',
 'Chloride',
 'BOD',
 'Status',
 'WQI']

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46528 entries, 0 to 46527
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   pH                      46528 non-null  float64
 1   Temperature             46528 non-null  float64
 2   Turbidity               0 non-null      float64
 3   Total Dissolved Solids  0 non-null      float64
 4   Conductivity            46528 non-null  float64
 5   Dissolved Oxygen        46528 non-null  float64
 6   Hardness                0 non-null      float64
 7   Nitrate                 0 non-null      float64
 8   Chloride                0 non-null      float64
 9   BOD                     0 non-null      float64
 10  Status                  46528 non-null  object
 11  WQI                     46528 non-null  float64
dtypes: float64(11), object(1)
memory usage: 4.3+ MB

Dataset10:

In [57]:
# Read Dataset02

sixth_dataset = os.path.join(dataset_folder, dataset_files[5])

df = pd.read_csv(sixth_dataset)

In [58]:
df.head()

,pH,Temperature,Turbidity,Total Dissolved Solids,Conductivity,Dissolved Oxygen,Hardness,Nitrate,Chloride,BOD,Target,WQI
0,7.85,7.5,NaN,NaN,134.5,9.95,NaN,0.255,NaN,0.15,NaN,27.143963
1,7.70,11.0,NaN,NaN,77.0,9.65,NaN,0.200,NaN,0.45,NaN,15.780001
2,7.65,7.5,NaN,NaN,101.5,9.90,NaN,0.100,NaN,0.55,NaN,20.612438
3,7.55,8.5,NaN,NaN,148.0,9.65,NaN,0.250,NaN,0.35,NaN,29.820475
4,7.80,10.0,NaN,NaN,106.0,9.55,NaN,0.150,NaN,0.25,NaN,21.498569

In [60]:
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 295
Columns : 12

In [61]:
df.columns.tolist()

['pH',
 'Temperature',
 'Turbidity',
 'Total Dissolved Solids',
 'Conductivity',
 'Dissolved Oxygen',
 'Hardness',
 'Nitrate',
 'Chloride',
 'BOD',
 'Target',
 'WQI']

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 295 entries, 0 to 294
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   pH                      295 non-null    float64
 1   Temperature             295 non-null    float64
 2   Turbidity               0 non-null      float64
 3   Total Dissolved Solids  0 non-null      float64
 4   Conductivity            295 non-null    float64
 5   Dissolved Oxygen        295 non-null    float64
 6   Hardness                0 non-null      float64
 7   Nitrate                 295 non-null    float64
 8   Chloride                0 non-null      float64
 9   BOD                     295 non-null    float64
 10  Target                  0 non-null      float64
 11  WQI                     295 non-null    float64
dtypes: float64(12)
memory usage: 27.8 KB

# Conclusion

In this notebook, the training datasets collected for the water quality prediction project were successfully analyzed and profiled. Each dataset was examined individually to understand its structure, including the number of rows and columns, available parameters, data types, missing values, and target variables. The analysis showed that although the datasets contain different combinations of water quality parameters, they follow a standardized column structure, making them suitable for further integration. This profiling process provided a clear understanding of the quality and characteristics of each dataset and established a strong foundation for the next phase of the project, which involves creating a master dataset by combining the relevant information from all selected training datasets.