# Dataset Comparison

## Objective

The objective of this notebook is to compare all the selected training datasets based on their structure, available water quality parameters, target variables, number of records, and data completeness. This comparison helps identify the contribution of each dataset and provides a clear strategy for creating a unified master dataset for machine learning.

## Theory

Different datasets collected from various sources contain different combinations of water quality parameters. Before creating a master dataset, it is essential to compare these datasets to identify common and unique parameters, missing values, target variables, and overall data quality. This comparison ensures that only relevant datasets and parameters are considered while creating the final master dataset, reducing complexity and improving consistency.

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
dataset_folder = "../../01_Datasets/Training Datasets"

dataset_files = sorted(
    [file for file in os.listdir(dataset_folder) if file.endswith(".csv")]
)

print("Training Datasets:\n")

for file in dataset_files:
    print(file)

Training Datasets:

Dataset01filtered.csv
Dataset02Filtered.csv
Dataset03Filtered.csv
Dataset04Filtered.csv
Dataset09Filtered.csv
Dataset10Filtered.csv

In [3]:
# Dictionary to store all datasets

datasets = {}

for file in dataset_files:
    file_path = os.path.join(dataset_folder, file)
    datasets[file] = pd.read_csv(file_path)

print("All datasets loaded successfully!")

All datasets loaded successfully!

In [4]:
print("Datasets Loaded:\n")

for name in datasets:
    print(name)

Datasets Loaded:

Dataset01filtered.csv
Dataset02Filtered.csv
Dataset03Filtered.csv
Dataset04Filtered.csv
Dataset09Filtered.csv
Dataset10Filtered.csv

In [5]:
comparison = []

In [6]:
for name, df in datasets.items():

    rows = df.shape[0]
    columns = df.shape[1]

    comparison.append({
        "Dataset": name,
        "Rows": rows,
        "Columns": columns
    })

In [7]:
comparison_df = pd.DataFrame(comparison)

comparison_df

                 Dataset     Rows  Columns
0  Dataset01filtered.csv      450       11
1  Dataset02Filtered.csv     1000       11
2  Dataset03Filtered.csv     2370       11
3  Dataset04Filtered.csv  1048575       14
4  Dataset09Filtered.csv    46528       12
5  Dataset10Filtered.csv      295       12

In [8]:
comparison = []

for name, df in datasets.items():

    comparison.append({
        "Dataset": name,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Target": "Yes" if "Target" in df.columns else "No",
        "WQI": "Yes" if "WQI" in df.columns else "No"
    })

comparison_df = pd.DataFrame(comparison)

comparison_df

                 Dataset     Rows  Columns Target  WQI
0  Dataset01filtered.csv      450       11    Yes   No
1  Dataset02Filtered.csv     1000       11    Yes   No
2  Dataset03Filtered.csv     2370       11    Yes   No
3  Dataset04Filtered.csv  1048575       14    Yes   No
4  Dataset09Filtered.csv    46528       12     No  Yes
5  Dataset10Filtered.csv      295       12    Yes  Yes

In [9]:
comparison = []

for name, df in datasets.items():

    comparison.append({
        "Dataset": name,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Duplicate Rows": df.duplicated().sum(),
        "Target": "Yes" if "Target" in df.columns else "No",
        "WQI": "Yes" if "WQI" in df.columns else "No"
    })

comparison_df = pd.DataFrame(comparison)

comparison_df

                 Dataset     Rows  Columns  Duplicate Rows Target  WQI
0  Dataset01filtered.csv      450       11               0    Yes   No
1  Dataset02Filtered.csv     1000       11               0    Yes   No
2  Dataset03Filtered.csv     2370       11             699    Yes   No
3  Dataset04Filtered.csv  1048575       14           21909    Yes   No
4  Dataset09Filtered.csv    46528       12             454     No  Yes
5  Dataset10Filtered.csv      295       12               0    Yes  Yes

In [10]:
comparison = []

for name, df in datasets.items():

    comparison.append({
        "Dataset": name,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Missing Values": df.isnull().sum().sum(),
        "Duplicate Rows": df.duplicated().sum(),
        "Target": "Yes" if "Target" in df.columns else "No",
        "WQI": "Yes" if "WQI" in df.columns else "No"
    })

comparison_df = pd.DataFrame(comparison)

comparison_df

,Dataset,Rows,Columns,Missing Values,Duplicate Rows,Target,WQI
0,Dataset01filtered.csv,450,11,1800,0,Yes,No
1,Dataset02Filtered.csv,1000,11,5000,0,Yes,No
2,Dataset03Filtered.csv,2370,11,20024,699,Yes,No
3,Dataset04Filtered.csv,1048575,14,3357702,21909,Yes,No
4,Dataset09Filtered.csv,46528,12,279168,454,No,Yes
5,Dataset10Filtered.csv,295,12,1475,0,Yes,Yes

In [11]:
comparison = []

# Standard parameters selected for our project
standard_parameters = [
    "pH",
    "Temperature",
    "Turbidity",
    "Total Dissolved Solids",
    "Conductivity",
    "Dissolved Oxygen",
    "Hardness",
    "Nitrate",
    "Chloride",
    "BOD",
    "Target",
    "WQI"
]

for name, df in datasets.items():

    available = []

    for parameter in standard_parameters:
        if parameter in df.columns:
            available.append(parameter)

    comparison.append({
        "Dataset": name,
        "Parameters Present": ", ".join(available)
    })

comparison_df = pd.DataFrame(comparison)

comparison_df

                 Dataset                                 Parameters Present
0  Dataset01filtered.csv  pH, Temperature, Turbidity, Total Dissolved So...
1  Dataset02Filtered.csv  pH, Temperature, Turbidity, Total Dissolved So...
2  Dataset03Filtered.csv  pH, Temperature, Turbidity, Total Dissolved So...
3  Dataset04Filtered.csv  pH, Temperature, Turbidity, Total Dissolved So...
4  Dataset09Filtered.csv  pH, Temperature, Turbidity, Total Dissolved So...
5  Dataset10Filtered.csv  pH, Temperature, Turbidity, Total Dissolved So...

In [12]:
comparison = []

for name, df in datasets.items():

    missing = []

    for parameter in standard_parameters:
        if parameter not in df.columns:
            missing.append(parameter)

    comparison.append({
        "Dataset": name,
        "Missing Parameters": ", ".join(missing)
    })

comparison_df = pd.DataFrame(comparison)

comparison_df

                 Dataset Missing Parameters
0  Dataset01filtered.csv                WQI
1  Dataset02Filtered.csv                WQI
2  Dataset03Filtered.csv                WQI
3  Dataset04Filtered.csv                WQI
4  Dataset09Filtered.csv             Target
5  Dataset10Filtered.csv

In [13]:
comparison = []

for name, df in datasets.items():

    available = []
    missing = []

    for parameter in standard_parameters:

        if parameter in df.columns:
            available.append(parameter)
        else:
            missing.append(parameter)

    comparison.append({

        "Dataset": name,

        "Rows": df.shape[0],

        "Columns": df.shape[1],

        "Missing Values": df.isnull().sum().sum(),

        "Duplicate Rows": df.duplicated().sum(),

        "Target": "Yes" if "Target" in df.columns else "No",

        "WQI": "Yes" if "WQI" in df.columns else "No",

        "Parameters Present": ", ".join(available),

        "Missing Parameters": ", ".join(missing)

    })

comparison_df = pd.DataFrame(comparison)

comparison_df

,Dataset,Rows,Columns,Missing Values,Duplicate Rows,Target,WQI,Parameters Present,Missing Parameters
0,Dataset01filtered.csv,450,11,1800,0,Yes,No,"pH, Temperature, Turbidity, Total Dissolved So...",WQI
1,Dataset02Filtered.csv,1000,11,5000,0,Yes,No,"pH, Temperature, Turbidity, Total Dissolved So...",WQI
2,Dataset03Filtered.csv,2370,11,20024,699,Yes,No,"pH, Temperature, Turbidity, Total Dissolved So...",WQI
3,Dataset04Filtered.csv,1048575,14,3357702,21909,Yes,No,"pH, Temperature, Turbidity, Total Dissolved So...",WQI
4,Dataset09Filtered.csv,46528,12,279168,454,No,Yes,"pH, Temperature, Turbidity, Total Dissolved So...",Target
5,Dataset10Filtered.csv,295,12,1475,0,Yes,Yes,"pH, Temperature, Turbidity, Total Dissolved So...",

In [14]:
comparison_df.to_csv(
    "../../08_Documentation/Dataset_Comparison_Report.csv",
    index=False
)

print("Dataset Comparison Report Saved Successfully!")

Dataset Comparison Report Saved Successfully!

# Conclusion

In this notebook, all selected training datasets were compared based on their structure, number of records, available parameters, missing values, duplicate records, and target variables. The comparison clearly identified the contribution of each dataset toward the final project and highlighted the differences in parameter availability across datasets. This analysis provides the necessary foundation for creating a unified master dataset by selecting and combining the most relevant information from each dataset. The generated comparison report will also serve as supporting documentation for future preprocessing, machine learning model development, and project reporting.