# Data Preprocessing

## Objective

The objective of this notebook is to prepare the master dataset for machine learning by identifying and handling missing values, duplicate records, inconsistent data, and other data quality issues. The preprocessing steps performed in this notebook will improve the quality of the dataset and ensure that it is suitable for exploratory data analysis, feature engineering, and machine learning model training.

## Theory

Data preprocessing is one of the most important stages in a machine learning pipeline. Real-world datasets often contain missing values, duplicate records, inconsistent formats, and noisy data. These issues can negatively affect the performance of machine learning models. Therefore, preprocessing is performed to improve data quality before model training while preserving meaningful information.

In [1]:
import pandas as pd
import numpy as np
import os

In [7]:
master_path = "../../01_Datasets/Master Dataset/Master_Dataset_v6.csv"

df = pd.read_csv(
    master_path,
    low_memory=False
)

print("Master Dataset Loaded Successfully!")

Master Dataset Loaded Successfully!

In [8]:
print("Shape of Dataset:")

print(df.shape)

Shape of Dataset:
(1099218, 12)

In [9]:
df.head()

,pH,Temperature,Turbidity,Total Dissolved Solids,Conductivity,Dissolved Oxygen,Hardness,Nitrate,Chloride,BOD,Target,WQI
0,7.42,16.88,0.25,306.7,1486.1,7.41,NaN,NaN,NaN,NaN,Good,NaN
1,8.18,20.55,0.87,84.3,476.3,6.04,NaN,NaN,NaN,NaN,Moderate,NaN
2,5.58,26.25,1.99,676.7,479.9,6.71,NaN,NaN,NaN,NaN,Poor,NaN
3,7.93,30.15,0.06,852.9,713.5,3.24,NaN,NaN,NaN,NaN,Poor,NaN
4,8.37,12.32,3.37,161.2,1702.6,6.83,NaN,NaN,NaN,NaN,Poor,NaN

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1099218 entries, 0 to 1099217
Data columns (total 12 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   pH                      1078893 non-null  float64
 1   Temperature             1069410 non-null  float64
 2   Turbidity               1041331 non-null  float64
 3   Total Dissolved Solids  1048727 non-null  float64
 4   Conductivity            1067045 non-null  float64
 5   Dissolved Oxygen        49793 non-null    float64
 6   Hardness                0 non-null        float64
 7   Nitrate                 1030175 non-null  float64
 8   Chloride                1017741 non-null  float64
 9   BOD                     1295 non-null     float64
 10  Target                  1050025 non-null  object
 11  WQI                     46823 non-null    float64
dtypes: float64(11), object(1)
memory usage: 100.6+ MB

In [11]:
df.describe()

,pH,Temperature,Turbidity,Total Dissolved Solids,Conductivity,Dissolved Oxygen,Hardness,Nitrate,Chloride,BOD,WQI
count,1.078893e+06,1.069410e+06,1.041331e+06,1.048727e+06,1.067045e+06,49793.000000,0.0,1.030175e+06,1.017741e+06,1295.000000,46823.000000
mean,7.553462e+00,1.944768e+01,4.948359e-01,2.649560e+02,4.204101e+02,8.128839,NaN,6.077093e+00,1.818660e+02,5.041316,29.497322
std,1.008613e+00,1.121798e+01,9.350441e-01,1.546918e+02,1.916423e+02,1.142189,NaN,3.132758e+00,6.576657e+01,4.947525,18.314122
min,3.000000e-01,0.000000e+00,1.410000e-14,1.064299e-02,0.000000e+00,0.000000,NaN,0.000000e+00,2.941350e+01,0.000000,0.524595
25%,6.939589e+00,1.159265e+01,3.704042e-02,1.318441e+02,2.840863e+02,7.897651,NaN,3.951510e+00,1.374347e+02,2.199779,22.742093
50%,7.499027e+00,1.696412e+01,2.004124e-01,2.636467e+02,3.960364e+02,7.987861,NaN,5.563875e+00,1.747464e+02,4.439111,29.024594
75%,8.073356e+00,2.498987e+01,5.951770e-01,3.950733e+02,5.277007e+02,8.185179,NaN,7.584356e+00,2.156446e+02,7.238340,33.663885
max,1.397159e+01,2.430051e+02,1.996778e+01,1.197000e+03,9.272000e+03,19.918926,NaN,7.307293e+01,1.430549e+03,123.500000,1834.549110

In [12]:
# Count missing values in each column

missing_values = df.isnull().sum()

missing_values

pH                          20325
Temperature                 29808
Turbidity                   57887
Total Dissolved Solids      50491
Conductivity                32173
Dissolved Oxygen          1049425
Hardness                  1099218
Nitrate                     69043
Chloride                    81477
BOD                       1097923
Target                      49193
WQI                       1052395
dtype: int64

In [13]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage = missing_percentage.round(2)

missing_percentage

pH                          1.85
Temperature                 2.71
Turbidity                   5.27
Total Dissolved Solids      4.59
Conductivity                2.93
Dissolved Oxygen           95.47
Hardness                  100.00
Nitrate                     6.28
Chloride                    7.41
BOD                        99.88
Target                      4.48
WQI                        95.74
dtype: float64

In [14]:
missing_report = pd.DataFrame({

    "Missing Values": df.isnull().sum(),

    "Missing Percentage": ((df.isnull().sum() / len(df)) * 100).round(2)

})

missing_report

                        Missing Values  Missing Percentage
pH                               20325                1.85
Temperature                      29808                2.71
Turbidity                        57887                5.27
Total Dissolved Solids           50491                4.59
Conductivity                     32173                2.93
Dissolved Oxygen               1049425               95.47
Hardness                       1099218              100.00
Nitrate                          69043                6.28
Chloride                         81477                7.41
BOD                            1097923               99.88
Target                           49193                4.48
WQI                            1052395               95.74

In [15]:
duplicates = df.duplicated().sum()

print("Duplicate Rows :", duplicates)

Duplicate Rows : 26500

In [16]:
print(df.dtypes)

pH                        float64
Temperature               float64
Turbidity                 float64
Total Dissolved Solids    float64
Conductivity              float64
Dissolved Oxygen          float64
Hardness                  float64
Nitrate                   float64
Chloride                  float64
BOD                       float64
Target                     object
WQI                       float64
dtype: object

In [17]:
print(df["Target"].value_counts(dropna=False))

Target
0           807847
1           240813
NaN          49193
2              915
Poor           358
Moderate        82
Good            10
Name: count, dtype: int64

In [18]:
print(df["WQI"].describe())

count    46823.000000
mean        29.497322
std         18.314122
min          0.524595
25%         22.742093
50%         29.024594
75%         33.663885
max       1834.549110
Name: WQI, dtype: float64

In [19]:
# Check relationship between Target and WQI

df.groupby("Target")["WQI"].describe()

          count  mean  std  min  25%  50%  75%  max
Target
0           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
1           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
2           0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
Good        0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
Moderate    0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
Poor        0.0   NaN  NaN  NaN  NaN  NaN  NaN  NaN

In [22]:
df = df.drop(columns=["Hardness", "BOD"])

print(df.shape)

(1099218, 10)

In [23]:
print(df.columns.tolist())

['pH', 'Temperature', 'Turbidity', 'Total Dissolved Solids', 'Conductivity', 'Dissolved Oxygen', 'Nitrate', 'Chloride', 'Target', 'WQI']

In [24]:
duplicate_percentage = (df.duplicated().sum() / len(df)) * 100

print("Duplicate Rows :", df.duplicated().sum())

print("Duplicate Percentage :", round(duplicate_percentage,2),"%")

Duplicate Rows : 26500
Duplicate Percentage : 2.41 %

In [25]:
df = df.drop_duplicates()

print(df.shape)

(1072718, 10)

In [26]:
print("Remaining Duplicates :", df.duplicated().sum())

Remaining Duplicates : 0

In [27]:
numerical_columns = [

    "pH",

    "Temperature",

    "Turbidity",

    "Total Dissolved Solids",

    "Conductivity",

    "Dissolved Oxygen",

    "Nitrate",

    "Chloride",

    "WQI"

]

print(df[numerical_columns].skew())

pH                         0.972906
Temperature                1.902232
Turbidity                  6.012026
Total Dissolved Solids     0.070824
Conductivity               0.985642
Dissolved Oxygen           1.187560
Nitrate                    2.259612
Chloride                   1.595958
WQI                       31.661011
dtype: float64

In [28]:
df[numerical_columns].describe()

,pH,Temperature,Turbidity,Total Dissolved Solids,Conductivity,Dissolved Oxygen,Nitrate,Chloride,WQI
count,1.052431e+06,1.042977e+06,1.015987e+06,1.023380e+06,1.041267e+06,49229.000000,1.004839e+06,992422.000000,46369.000000
mean,7.555783e+00,1.945181e+01,4.935877e-01,2.648764e+02,4.203082e+02,8.130753,6.072979e+00,181.751827,29.542293
std,1.009866e+00,1.121411e+01,9.343755e-01,1.546257e+02,1.917068e+02,1.138848,3.126773e+00,65.621856,18.375820
min,3.000000e-01,0.000000e+00,1.410000e-14,1.064299e-02,0.000000e+00,0.000000,0.000000e+00,29.413497,0.524595
25%,6.941245e+00,1.159813e+01,3.698829e-02,1.318396e+02,2.840302e+02,7.897736,3.950249e+00,137.405852,22.762953
50%,7.500000e+00,1.697046e+01,2.000475e-01,2.635912e+02,3.959920e+02,7.987445,5.561756e+00,174.687793,29.055156
75%,8.074376e+00,2.500258e+01,5.938426e-01,3.949460e+02,5.275627e+02,8.184740,7.581232e+00,215.537506,33.683065
max,1.397159e+01,2.430051e+02,1.996778e+01,1.197000e+03,9.272000e+03,19.918926,7.307293e+01,1430.548852,1834.549110

In [29]:
missing_report = pd.DataFrame({

    "Missing Values": df.isnull().sum(),

    "Missing Percentage":
        (df.isnull().sum()/len(df)*100).round(2)

})

missing_report

                        Missing Values  Missing Percentage
pH                               20287                1.89
Temperature                      29741                2.77
Turbidity                        56731                5.29
Total Dissolved Solids           49338                4.60
Conductivity                     31451                2.93
Dissolved Oxygen               1023489               95.41
Nitrate                          67879                6.33
Chloride                         80296                7.49
Target                           48040                4.48
WQI                            1026349               95.68

In [31]:
median_columns = [

    "pH",

    "Temperature",

    "Turbidity",

    "Conductivity",

    "Nitrate",

    "Chloride"

]

for column in median_columns:

    df[column] = df[column].fillna(
        df[column].median()
    )

print("Median Imputation Completed")

Median Imputation Completed

In [32]:
df["Total Dissolved Solids"] = df["Total Dissolved Solids"].fillna(

    df["Total Dissolved Solids"].mean()

)

print("Mean Imputation Completed Successfully!")

Mean Imputation Completed Successfully!

In [33]:
missing_report = pd.DataFrame({

    "Missing Values": df.isnull().sum(),

    "Missing Percentage":
        (df.isnull().sum() / len(df) * 100).round(2)

})

missing_report

                        Missing Values  Missing Percentage
pH                                   0                0.00
Temperature                          0                0.00
Turbidity                            0                0.00
Total Dissolved Solids               0                0.00
Conductivity                         0                0.00
Dissolved Oxygen               1023489               95.41
Nitrate                              0                0.00
Chloride                             0                0.00
Target                           48040                4.48
WQI                            1026349               95.68

In [34]:
print("Dataset Shape:")

print(df.shape)

Dataset Shape:
(1072718, 10)

In [35]:
print(df.dtypes)

pH                        float64
Temperature               float64
Turbidity                 float64
Total Dissolved Solids    float64
Conductivity              float64
Dissolved Oxygen          float64
Nitrate                   float64
Chloride                  float64
Target                     object
WQI                       float64
dtype: object

In [36]:
output_folder = "../../01_Datasets/Preprocessed Dataset"

os.makedirs(output_folder, exist_ok=True)

save_path = os.path.join(
    output_folder,
    "Master_Dataset_Preprocessed.csv"
)

df.to_csv(
    save_path,
    index=False
)

print("Preprocessed Dataset Saved Successfully!")
print("Location:", save_path)

Preprocessed Dataset Saved Successfully!
Location: ../../01_Datasets/Preprocessed Dataset\Master_Dataset_Preprocessed.csv

In [37]:
df_check = pd.read_csv(
    save_path,
    low_memory=False
)

print("Verification Successful!")

print()

print(df_check.shape)

Verification Successful!

(1072718, 10)

In [38]:
df_check.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1072718 entries, 0 to 1072717
Data columns (total 10 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   pH                      1072718 non-null  float64
 1   Temperature             1072718 non-null  float64
 2   Turbidity               1072718 non-null  float64
 3   Total Dissolved Solids  1072718 non-null  float64
 4   Conductivity            1072718 non-null  float64
 5   Dissolved Oxygen        49229 non-null    float64
 6   Nitrate                 1072718 non-null  float64
 7   Chloride                1072718 non-null  float64
 8   Target                  1024678 non-null  object
 9   WQI                     46369 non-null    float64
dtypes: float64(9), object(1)
memory usage: 81.8+ MB

In [39]:
df_check.head()

,pH,Temperature,Turbidity,Total Dissolved Solids,Conductivity,Dissolved Oxygen,Nitrate,Chloride,Target,WQI
0,7.42,16.88,0.25,306.7,1486.1,7.41,5.561756,174.687793,Good,NaN
1,8.18,20.55,0.87,84.3,476.3,6.04,5.561756,174.687793,Moderate,NaN
2,5.58,26.25,1.99,676.7,479.9,6.71,5.561756,174.687793,Poor,NaN
3,7.93,30.15,0.06,852.9,713.5,3.24,5.561756,174.687793,Poor,NaN
4,8.37,12.32,3.37,161.2,1702.6,6.83,5.561756,174.687793,Poor,NaN

# Conclusion

In this notebook, the master dataset was successfully preprocessed to improve its quality for machine learning. Columns with extremely high missing values (Hardness and BOD) were removed, duplicate records were eliminated, and missing values in important numerical features were handled using appropriate statistical imputation methods. Median imputation was applied to skewed features, while mean imputation was used for the approximately symmetric Total Dissolved Solids feature. The preprocessed dataset was validated and saved successfully, making it ready for exploratory data analysis and feature engineering.