# Feature Engineering

## Objective

The objective of this notebook is to prepare the preprocessed water quality dataset for machine learning by selecting relevant features, transforming variables when necessary, and creating a final dataset suitable for model training and evaluation.

## Theory

Feature engineering is the process of selecting, transforming, and preparing input variables for machine learning models. Proper feature engineering improves model performance by ensuring that relevant information is retained while unnecessary or inconsistent features are removed.

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
dataset_path = "../../01_Datasets/Preprocessed Dataset/Master_Dataset_Preprocessed.csv"

df = pd.read_csv(
    dataset_path,
    low_memory=False
)

print("Preprocessed Dataset Loaded Successfully!")

Preprocessed Dataset Loaded Successfully!

In [3]:
print("Dataset Shape:")
print(df.shape)

df.info()

Dataset Shape:
(1072718, 10)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1072718 entries, 0 to 1072717
Data columns (total 10 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   pH                      1072718 non-null  float64
 1   Temperature             1072718 non-null  float64
 2   Turbidity               1072718 non-null  float64
 3   Total Dissolved Solids  1072718 non-null  float64
 4   Conductivity            1072718 non-null  float64
 5   Dissolved Oxygen        49229 non-null    float64
 6   Nitrate                 1072718 non-null  float64
 7   Chloride                1072718 non-null  float64
 8   Target                  1024678 non-null  object
 9   WQI                     46369 non-null    float64
dtypes: float64(9), object(1)
memory usage: 81.8+ MB

In [4]:
df.head()

,pH,Temperature,Turbidity,Total Dissolved Solids,Conductivity,Dissolved Oxygen,Nitrate,Chloride,Target,WQI
0,7.42,16.88,0.25,306.7,1486.1,7.41,5.561756,174.687793,Good,NaN
1,8.18,20.55,0.87,84.3,476.3,6.04,5.561756,174.687793,Moderate,NaN
2,5.58,26.25,1.99,676.7,479.9,6.71,5.561756,174.687793,Poor,NaN
3,7.93,30.15,0.06,852.9,713.5,3.24,5.561756,174.687793,Poor,NaN
4,8.37,12.32,3.37,161.2,1702.6,6.83,5.561756,174.687793,Poor,NaN

In [5]:
print(df["Target"].unique())

['Good' 'Moderate' 'Poor' '2' '1' '0' nan]

In [6]:
quality_labels = ["Good", "Moderate", "Poor"]

quality_df = df[
    df["Target"].isin(quality_labels)
].copy()

print("Quality Dataset Shape:")
print(quality_df.shape)

Quality Dataset Shape:
(450, 10)

In [7]:
quality_df["Target"].value_counts()

Target
Poor        358
Moderate     82
Good         10
Name: count, dtype: int64

In [8]:
training_folder = "../../02_Machine Learning/Training"

os.makedirs(training_folder, exist_ok=True)

quality_df.to_csv(
    os.path.join(
        training_folder,
        "Quality_Model_Dataset.csv"
    ),
    index=False
)

print("Quality Dataset Saved Successfully!")

Quality Dataset Saved Successfully!

In [9]:
potability_labels = ["0", "1"]

potability_df = df[
    df["Target"].isin(potability_labels)
].copy()

print("Potability Dataset Shape:")
print(potability_df.shape)

Potability Dataset Shape:
(1023313, 10)

In [10]:
potability_df["Target"].value_counts()

Target
0    791403
1    231910
Name: count, dtype: int64

In [13]:
potability_df.to_csv(
    os.path.join(
        training_folder,
        "Potability_Model_Dataset.csv"
    ),
    index=False
)

print("Potability Dataset Saved Successfully!")

Potability Dataset Saved Successfully!

In [14]:
comparison = pd.DataFrame({

    "Dataset": [
        "Quality Model",
        "Potability Model"
    ],

    "Rows": [
        len(quality_df),
        len(potability_df)
    ],

    "Columns": [
        quality_df.shape[1],
        potability_df.shape[1]
    ]

})

comparison

            Dataset     Rows  Columns
0     Quality Model      450       10
1  Potability Model  1023313       10

In [15]:
table_folder = "../../08_Documentation/Tables"

os.makedirs(table_folder, exist_ok=True)

comparison.to_csv(
    os.path.join(
        table_folder,
        "Model_Dataset_Comparison.csv"
    ),
    index=False
)

print("Comparison Table Saved Successfully!")

Comparison Table Saved Successfully!

In [16]:
potability_path = "../../02_Machine Learning/Training/Potability_Model_Dataset.csv"

potability_df = pd.read_csv(
    potability_path,
    low_memory=False
)

print("Potability Dataset Loaded Successfully!")

Potability Dataset Loaded Successfully!

In [17]:
print(potability_df.shape)

potability_df.info()

(1023313, 10)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1023313 entries, 0 to 1023312
Data columns (total 10 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   pH                      1023313 non-null  float64
 1   Temperature             1023313 non-null  float64
 2   Turbidity               1023313 non-null  float64
 3   Total Dissolved Solids  1023313 non-null  float64
 4   Conductivity            1023313 non-null  float64
 5   Dissolved Oxygen        85 non-null       float64
 6   Nitrate                 1023313 non-null  float64
 7   Chloride                1023313 non-null  float64
 8   Target                  1023313 non-null  int64
 9   WQI                     0 non-null        float64
dtypes: float64(9), int64(1)
memory usage: 78.1 MB

In [18]:
missing_report = pd.DataFrame({

    "Missing Values": potability_df.isnull().sum(),

    "Missing Percentage":
    (potability_df.isnull().sum()/len(potability_df)*100).round(2)

})

missing_report

                        Missing Values  Missing Percentage
pH                                   0                0.00
Temperature                          0                0.00
Turbidity                            0                0.00
Total Dissolved Solids               0                0.00
Conductivity                         0                0.00
Dissolved Oxygen               1023228               99.99
Nitrate                              0                0.00
Chloride                             0                0.00
Target                               0                0.00
WQI                            1023313              100.00

In [19]:
potability_df["Target"] = potability_df["Target"].astype(int)

print(potability_df["Target"].dtype)

int32

In [20]:
feature_columns = [

    "pH",
    "Temperature",
    "Turbidity",
    "Total Dissolved Solids",
    "Conductivity",
    "Dissolved Oxygen",
    "Nitrate",
    "Chloride"

]

X = potability_df[feature_columns]

y = potability_df["Target"]

print("Features Shape :", X.shape)
print("Target Shape :", y.shape)

Features Shape : (1023313, 8)
Target Shape : (1023313,)

In [22]:
X.head()

,pH,Temperature,Turbidity,Total Dissolved Solids,Conductivity,Dissolved Oxygen,Nitrate,Chloride
0,6.673190,22.140587,7.947823,264.876366,395.992045,5.818803,5.561756,174.687793
1,7.082763,15.583395,6.210030,264.876366,395.992045,3.769910,5.561756,174.687793
2,6.123126,33.368529,9.068397,264.876366,395.992045,5.804770,5.561756,174.687793
3,6.951184,22.142423,5.193508,264.876366,395.992045,7.251277,5.561756,174.687793
4,8.989060,20.020028,4.350675,264.876366,395.992045,6.497510,5.561756,174.687793

In [24]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: Target, dtype: int32

# Conclusion

In this notebook, the preprocessed master dataset was transformed into separate model-ready datasets for water quality classification and water potability prediction. The potability dataset was selected as the primary dataset for machine learning due to its large number of labeled samples. The datasets were successfully saved and prepared for model training.